baseURL = "https://ndesignstudyosu.com.tr/"
title = "N Design Studio"
defaultContentLanguage = "ar"
defaultContentLanguageInSubdir = true

############################################
# LANGUAGES
############################################

[languages]

############################################
# ARABIC (DEFAULT)
############################################
[languages.ar]
languageName = "العربية"
weight = 1
contentDir = "content/ar"
title = "N Design Studio"
languageCode = "ar"
direction = "rtl"

[languages.ar.params]
homepageLayout = "Arabic-home"

[languages.ar.menu]
  [[languages.ar.menu.main]]
  name = "من نحن"
  url = "/ar/about/"
  weight = 1

  [[languages.ar.menu.main]]
  name = "تواصل"
  url = "/ar/contact/"
  weight = 2

  [[languages.ar.menu.main]]
  name = "Blog"
  url = "/ar/posts/"
  weight = 3

############################################
# ENGLISH
############################################
[languages.en]
languageName = "English"
weight = 2
contentDir = "content/en"
title = "N Design Studio"
languageCode = "en"

[languages.en.params]
homepageLayout = "English-home"

[languages.en.menu]
  [[languages.en.menu.main]]
  name = "About"
  url = "/en/about/"
  weight = 1

  [[languages.en.menu.main]]
  name = "Contact"
  url = "/en/contact/"
  weight = 2

  [[languages.en.menu.main]]
  name = "Blog"
  url = "/en/posts/"
  weight = 3

############################################
# TURKISH
############################################
[languages.tr]
languageName = "Türkçe"
weight = 3
contentDir = "content/tr"
title = "N Design Studio"
languageCode = "tr"

[languages.tr.params]
homepageLayout = "Turkish-home"

[languages.tr.menu]
  [[languages.tr.menu.main]]
  name = "Hakkında"
  url = "/tr/about/"
  weight = 1

  [[languages.tr.menu.main]]
  name = "İletişim"
  url = "/tr/contact/"
  weight = 2

  [[languages.tr.menu.main]]
  name = "Blog"
  url = "/tr/posts/"
  weight = 3

############################################
# SOCIALS
############################################
[[params.socials]]
name = "instagram"
link = "https://instagram.com/ndesignstudyosu/"

[[params.socials]]
name = "twitter"
link = "https://twitter.com/NDesignStudyosu"

[[params.socials]]
name = "linkedin"
link = "https://linkedin.com/in/NDesignStudyosu"

[[params.socials]]
name = "youtube"
link = "https://youtube.com/@ndesignstudyosu8359"

[[params.socials]]
name = "tiktok"
link = "https://tiktok.com/@ndesignstudyosu"

############################################
# MARKUP
############################################
[markup.goldmark.renderer]
unsafe = true

############################################
# TAXONOMIES
############################################
[taxonomies]
category = "categories"

############################################
# BUILD CONFIGURATION
############################################
[build]
  writeStats = true

[asset]
  [asset.sass]
    use = "dartsass"
